apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: ${serviceName}-service
spec:
  exportTo:
    - .
  hosts: ${serviceUrl}
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: HTTPS
    - name: http
      number: 80
      protocol: HTTP
  resolution: DNS
