apiVersion: v2.edp.epam.com/v1alpha1
kind: Codebase
metadata:
  name: history-excerptor
spec:
  emptyProject: false
  commitMessagePattern: null
  jenkinsSlave: dataplatform-jenkins-agent
  gitUrlPath: null
  defaultBranch: master
  buildTool: none
  route: null
  perf: null
  versioning:
    startFrom: 0.0.1
    type: edp
  jobProvisioning: registry
  repository:
    url: ${repoUrl}
  lang: groovy-pipeline
  deploymentScript: ''
  strategy: clone
  jiraIssueMetadataPayload: null
  gitServer: gerrit
  testReportFramework: null
  ticketNamePattern: null
  type: library
  database: null
  description: null
  framework: null
  ciTool: Jenkins